#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file_path=$1
    server_ip=$2
    user_name=$3
    ssh_key=$4

    mkdir -p ~/.ssh
    echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    chmod 600 ~/.ssh/config
    scp -i "$ssh_key" "$file_path" "$user_name@$server_ip:~/"
fi
