#!/usr/bin/env bash
#configure web-02 to be identical to web-01 & add a custom Nginx response header
sudo apt update
sudo apt-get -y install nginx
sudo netstat -tuln | grep ":80.*LISTEN"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html 
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /etc/nginx//nginx.conf
sed -i '/http {/a \        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
