#!/usr/bin/env bash
# Bash script that installs nginx & changes the welcome page

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
