#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.

function cleanup() 
{
    echo "I am invincible!!!"
    exit 0
}
trap cleanup SIGTERM
i=1
while [ $i -le 10 ]
do 
	echo "To infinity and beyond"
	sleep 2
	echo "I am invincible!!!"
done
