#!/usr/bin/env bash
# This script is display numbers from 1 - 100
number=1
while [ $number -le 100 ]
do
	echo "$number"
	if [ $(($number%3)) == 0 ]
	then
		echo "Fizz"
	elif [ $(($number%5 == 0)) ] 
        then
                echo "Buzz"
	elif [ $(($number%3 == 0)) ] && [ $(($number%5==0)) ]
        then
                echo "FizzBuzz"
	fi
	number=$(( number+1 ))
done
