#!/usr/bin/env bash
# This script is display numbers from 1 - 100
number=1
while [ $number -le 100 ]
do
	if ((number%3 == 0 ))  && ((number%5 == 0 ))
	then
		echo "FizzBuzz"
	elif ((number%5 == 0))
        then
                echo "Buzz"
	elif ((number%3 == 0))
        then
                echo "Fizz"
	else
		echo "$number"
	fi
	number=$(( number+1 ))
done
