#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
number=1
while [ $number -le 10 ]
do
	if [ $number = 4 ]
	then
		echo "bad luck"
	elif [ $number = 8 ]
        then
                echo "good luck"
	else
		echo "Best School"
	fi
	number=$(( number+1 ))
done
