#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
number=1
while [ $number -le 20 ]
do
	echo "$number"
	if [ $number = 4 ]
	then
		echo "bad luck from China"
	elif [ $number = 9 ]
        then
                echo "bad luck from Japan"
	elif [ $number = 17 ]
        then
                echo "bad luck from Italy"
	fi
	number=$(( number+1 ))
done
