#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
number=0
while [ $number -le 12 ]
do 
	echo "Hour: $number"
	i=1
	while [ $i -le 60 ]
	do
		echo "$i"
		i=$(( i+1 ))
		if [ $i = 60 ]
		then
			break
		fi
	done
	number=$(( number+1 ))
done
