#!/usr/bin/env bash
# This script is displaying The content of the current directory in a list format

for file in *
do
    if [ "${file:0:1}" != "." ]
    then
        name="$(echo "$file" | cut -d'-' -f2-)"
	echo "$name"
    fi
done

